/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.28
 * Generated at: 2025-04-16 10:09:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.page;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\" />\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"/>\r\n");
      out.write("<title>Dawn Airlines</title>\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/airline.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"Home\" >\r\n");
      out.write("\r\n");
      out.write("  <!-- Navbar -->\r\n");
      out.write("  <header class=\"navbar\">\r\n");
      out.write("    <div class=\"logo\">Dawn Airlines</div>\r\n");
      out.write("    <nav>\r\n");
      out.write("  <ul>\r\n");
      out.write("    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/home\" class=\"active\">Home</a></li>\r\n");
      out.write("    \r\n");
      out.write("    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/contact\">Contact Us</a></li>\r\n");
      out.write("    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/About\">About Us</a></li>\r\n");
      out.write("    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/login\">login</a></li>\r\n");
      out.write("  </ul>\r\n");
      out.write("</nav>\r\n");
      out.write("  </header>\r\n");
      out.write("\r\n");
      out.write("  <!-- Hero Section -->\r\n");
      out.write("  <section class=\"hero\">\r\n");
      out.write("    <div class=\"hero-content\">\r\n");
      out.write("      <h1>Fly the Future with Dawn Airlines</h1>\r\n");
      out.write("      <p>Experience comfort, speed, and reliability on every journey.</p>\r\n");
      out.write("      <a href=\"#\" class=\"btn\">Book Now</a>\r\n");
      out.write("    </div>\r\n");
      out.write("  </section>\r\n");
      out.write("\r\n");
      out.write("  <!-- Booking Form Section -->\r\n");
      out.write("  <section class=\"booking-section\">\r\n");
      out.write("    <div class=\"booking-form\">\r\n");
      out.write("      <h2>Book Your Flight</h2>\r\n");
      out.write("      <form>\r\n");
      out.write("        <input type=\"text\" placeholder=\"From\" required />\r\n");
      out.write("        <input type=\"text\" placeholder=\"To\" required />\r\n");
      out.write("        <input type=\"date\" placeholder=\"Departure\" required />\r\n");
      out.write("        <input type=\"date\" placeholder=\"Return\" />\r\n");
      out.write("        <button type=\"submit\">Search Flights</button>\r\n");
      out.write("      </form>\r\n");
      out.write("    </div>\r\n");
      out.write("  </section>\r\n");
      out.write("\r\n");
      out.write("  <!-- Features Section -->\r\n");
      out.write("  <section class=\"features\">\r\n");
      out.write("    <h2>Why Choose Dawn Airlines</h2>\r\n");
      out.write("    <div class=\"features-container\">\r\n");
      out.write("      <div class=\"feature\">\r\n");
      out.write("        <img src=\"direct_flights.jpg\" alt=\"Direct Flights\">\r\n");
      out.write("        <h3>Direct Flights Worldwide</h3>\r\n");
      out.write("        <p>Connect to over 80 cities directly with ease and comfort.</p>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"feature\">\r\n");
      out.write("        <img src=\"modern-fleet.jpg\" alt=\"Modern Fleet\">\r\n");
      out.write("        <h3>Modern, Comfortable Aircraft</h3>\r\n");
      out.write("        <p>Fly with our latest aircraft models ensuring safety and comfort.</p>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"feature\">\r\n");
      out.write("        <img src=\"experienced-crew.jpg\" alt=\"Experienced Crew\">\r\n");
      out.write("        <h3>Experienced, Qualified Crew</h3>\r\n");
      out.write("        <p>Our professional crew is dedicated to providing exceptional service.</p>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"feature\">\r\n");
      out.write("        <img src=\"loyalty-program.jpg\" alt=\"Loyalty Program\">\r\n");
      out.write("        <h3>Rewarding Loyalty Program</h3>\r\n");
      out.write("        <p>Earn miles and enjoy exclusive benefits every time you travel with us.</p>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </section>\r\n");
      out.write("\r\n");
      out.write("  <!-- Footer -->\r\n");
      out.write("  <footer class=\"footer\">\r\n");
      out.write("    <div class=\"footer-container\">\r\n");
      out.write("      <div class=\"footer-col\">\r\n");
      out.write("        <h4>About Us</h4>\r\n");
      out.write("        <ul>\r\n");
      out.write("          <li><a href=\"#\">News</a></li>\r\n");
      out.write("          <li><a href=\"#\">Annual Report</a></li>\r\n");
      out.write("          <li><a href=\"#\">Careers</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"footer-col\">\r\n");
      out.write("        <h4>Contact Us</h4>\r\n");
      out.write("        <ul>\r\n");
      out.write("          <li><a href=\"#\">Contact with us</a></li>\r\n");
      out.write("          <li><a href=\"#\">Feedback</a></li>\r\n");
      out.write("          <li><a href=\"#\">Login</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"footer-col subscribe\">\r\n");
      out.write("        <h4>Subscribe to our offers</h4>\r\n");
      out.write("        <p>Subscribe and be the first to hear about the latest offers</p>\r\n");
      out.write("        <div class=\"subscribe-form\">\r\n");
      out.write("          <input type=\"email\" placeholder=\"Enter Your Email address\">\r\n");
      out.write("          <button>Subscribe</button>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </footer>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
